/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['.card[_ngcontent-%COMP%] {\r\n  margin: 5vw;\r\n}\r\n\r\n.header-image[_ngcontent-%COMP%] {\r\n  background-image: url(\'/favicon.ico\');\r\n  background-size: cover;\r\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvcHJpbmMvRGVza3RvcC9vem1lbnRhMmsxNy9hc3NldHMvYXBwL2NvbXBvbmVudHMvY29udGFjdHNwYWdlL2NvbnRhY3RzcGFnZS5jb21wb25lbnQuY3NzLnNoaW0ubmdzdHlsZS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L1VzZXJzL3ByaW5jL0Rlc2t0b3Avb3ptZW50YTJrMTcvYXNzZXRzL2FwcC9jb21wb25lbnRzL2NvbnRhY3RzcGFnZS9jb250YWN0c3BhZ2UuY29tcG9uZW50LmNzcyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7In0=
