/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './nteventpage.component.css.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from './nteventpage.component';
const styles_NTEventPageComponent:any[] = [i0.styles];
export const RenderType_NTEventPageComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_NTEventPageComponent,data:{}});
export function View_NTEventPageComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'h1',([] as any[]),
      (null as any),(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i1.ɵted((null as any),['This is not technical events page']))],(null as any),
      (null as any));
}
export function View_NTEventPageComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'app-nteventpage',
      ([] as any[]),(null as any),(null as any),(null as any),View_NTEventPageComponent_0,
      RenderType_NTEventPageComponent)),i1.ɵdid(49152,(null as any),0,i2.NTEventPageComponent,
      ([] as any[]),(null as any),(null as any))],(null as any),(null as any));
}
export const NTEventPageComponentNgFactory:i1.ComponentFactory<i2.NTEventPageComponent> = i1.ɵccf('app-nteventpage',
    i2.NTEventPageComponent,View_NTEventPageComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvU2hlcmluL096bWVudGEySzE3L2Fzc2V0cy9hcHAvY29tcG9uZW50cy9udGV2ZW50cGFnZS9udGV2ZW50cGFnZS5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vQzovVXNlcnMvU2hlcmluL096bWVudGEySzE3L2Fzc2V0cy9hcHAvY29tcG9uZW50cy9udGV2ZW50cGFnZS9udGV2ZW50cGFnZS5jb21wb25lbnQudHMiLCJuZzovLy9DOi9Vc2Vycy9TaGVyaW4vT3ptZW50YTJLMTcvYXNzZXRzL2FwcC9jb21wb25lbnRzL250ZXZlbnRwYWdlL250ZXZlbnRwYWdlLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vQzovVXNlcnMvU2hlcmluL096bWVudGEySzE3L2Fzc2V0cy9hcHAvY29tcG9uZW50cy9udGV2ZW50cGFnZS9udGV2ZW50cGFnZS5jb21wb25lbnQudHMuTlRFdmVudFBhZ2VDb21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCI8aDE+VGhpcyBpcyBub3QgdGVjaG5pY2FsIGV2ZW50cyBwYWdlPC9oMT4iLCI8YXBwLW50ZXZlbnRwYWdlPjwvYXBwLW50ZXZlbnRwYWdlPiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7OztvQkNBQTtNQUFBLHdFQUFJO2FBQUE7Ozs7b0JDQUo7TUFBQTtxQ0FBQSxVQUFBO01BQUE7OzsifQ==
