/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './homepage.component.css.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from './homepage.component';
const styles_HomePageComponent:any[] = [i0.styles];
export const RenderType_HomePageComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_HomePageComponent,data:{}});
export function View_HomePageComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,([] as any[]),(null as any),(null as any));
}
export function View_HomePageComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'app-homepage',
      ([] as any[]),(null as any),(null as any),(null as any),View_HomePageComponent_0,
      RenderType_HomePageComponent)),i1.ɵdid(49152,(null as any),0,i2.HomePageComponent,
      ([] as any[]),(null as any),(null as any))],(null as any),(null as any));
}
export const HomePageComponentNgFactory:i1.ComponentFactory<i2.HomePageComponent> = i1.ɵccf('app-homepage',
    i2.HomePageComponent,View_HomePageComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvU2hlcmluL096bWVudGEySzE3L2Fzc2V0cy9hcHAvY29tcG9uZW50cy9ob21lcGFnZS9ob21lcGFnZS5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vQzovVXNlcnMvU2hlcmluL096bWVudGEySzE3L2Fzc2V0cy9hcHAvY29tcG9uZW50cy9ob21lcGFnZS9ob21lcGFnZS5jb21wb25lbnQudHMiLCJuZzovLy9DOi9Vc2Vycy9TaGVyaW4vT3ptZW50YTJLMTcvYXNzZXRzL2FwcC9jb21wb25lbnRzL2hvbWVwYWdlL2hvbWVwYWdlLmNvbXBvbmVudC50cy5Ib21lUGFnZUNvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjxhcHAtaG9tZXBhZ2U+PC9hcHAtaG9tZXBhZ2U+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7O29CQ0FBO01BQUE7a0NBQUEsVUFBQTtNQUFBOzs7In0=
