/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './more.component.css.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from './more.component';
import * as i3 from '@angular/material';
const styles_MoreComponent:any[] = [i0.styles];
export const RenderType_MoreComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_MoreComponent,data:{}});
export function View_MoreComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),0,'p',([] as any[]),
      [[8,'innerHTML',1]],(null as any),(null as any),(null as any),(null as any)))],
      (null as any),(_ck,_v) => {
        var _co:i2.MoreComponent = _v.component;
        const currVal_0:any = _co.data;
        _ck(_v,0,0,currVal_0);
      });
}
export function View_MoreComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'app-more',([] as any[]),
      (null as any),(null as any),(null as any),View_MoreComponent_0,RenderType_MoreComponent)),
      i1.ɵdid(49152,(null as any),0,i2.MoreComponent,[i3.MdDialogRef,i3.MD_DIALOG_DATA],
          (null as any),(null as any))],(null as any),(null as any));
}
export const MoreComponentNgFactory:i1.ComponentFactory<i2.MoreComponent> = i1.ɵccf('app-more',
    i2.MoreComponent,View_MoreComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvcHJpbmMvRGVza3RvcC9vem1lbnRhMmsxNy9hc3NldHMvYXBwL2NvbXBvbmVudHMvbW9yZS9tb3JlLmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9Vc2Vycy9wcmluYy9EZXNrdG9wL296bWVudGEyazE3L2Fzc2V0cy9hcHAvY29tcG9uZW50cy9tb3JlL21vcmUuY29tcG9uZW50LnRzIiwibmc6Ly8vQzovVXNlcnMvcHJpbmMvRGVza3RvcC9vem1lbnRhMmsxNy9hc3NldHMvYXBwL2NvbXBvbmVudHMvbW9yZS9tb3JlLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vQzovVXNlcnMvcHJpbmMvRGVza3RvcC9vem1lbnRhMmsxNy9hc3NldHMvYXBwL2NvbXBvbmVudHMvbW9yZS9tb3JlLmNvbXBvbmVudC50cy5Nb3JlQ29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiPHAgW2lubmVySFRNTF09XCJkYXRhXCI+PC9wPiIsIjxhcHAtbW9yZT48L2FwcC1tb3JlPiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7b0JDQUE7TUFBQTs7O1FBQUc7UUFBSCxXQUFHLFNBQUg7Ozs7b0JDQUE7TUFBQTthQUFBO1VBQUE7OzsifQ==
