/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['.app-sidenav[_ngcontent-%COMP%] {\r\n  padding: 10px;\r\n  min-width: 200px;\r\n}\r\n\r\n.app-filler[_ngcontent-%COMP%] {\r\n  flex: 1 1 auto;\r\n}\r\n#heading[_ngcontent-%COMP%]{\r\n  font-family: Helvetica;\r\n  font-size: xx-large;\r\n}\r\n\r\n.app-icon-button[_ngcontent-%COMP%] {\r\n  color: white;\r\n  box-shadow: none;\r\n  user-select: none;\r\n  background: none;\r\n  border: none;\r\n  cursor: pointer;\r\n  filter: none;\r\n  font-weight: normal;\r\n  height: auto;\r\n  line-height: inherit;\r\n  margin: 0;\r\n  font-family: Helvetica;\r\n  min-width: 0;\r\n  padding: 0;\r\n  text-align: left;\r\n  text-decoration: none;\r\n  margin-right: 10px;\r\n  margin-top: 8px;\r\n}\r\nspan[_ngcontent-%COMP%]{\r\n  font-family: Helvetica;\r\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvcHJpbmMvRGVza3RvcC9vem1lbnRhMmsxNy9hc3NldHMvYXBwL2NvbXBvbmVudHMvc2lkZW5hdi9zaWRlbmF2LmNvbXBvbmVudC5jc3Muc2hpbS5uZ3N0eWxlLnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vQzovVXNlcnMvcHJpbmMvRGVza3RvcC9vem1lbnRhMmsxNy9hc3NldHMvYXBwL2NvbXBvbmVudHMvc2lkZW5hdi9zaWRlbmF2LmNvbXBvbmVudC5jc3MiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7OyJ9
