/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './eventpage.component.css.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from './eventpage.component';
const styles_EventPageComponent:any[] = [i0.styles];
export const RenderType_EventPageComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_EventPageComponent,data:{}});
export function View_EventPageComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,([] as any[]),(null as any),(null as any));
}
export function View_EventPageComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'app-eventpage',
      ([] as any[]),(null as any),(null as any),(null as any),View_EventPageComponent_0,
      RenderType_EventPageComponent)),i1.ɵdid(49152,(null as any),0,i2.EventPageComponent,
      ([] as any[]),(null as any),(null as any))],(null as any),(null as any));
}
export const EventPageComponentNgFactory:i1.ComponentFactory<i2.EventPageComponent> = i1.ɵccf('app-eventpage',
    i2.EventPageComponent,View_EventPageComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvU2hlcmluL096bWVudGEySzE3L2Fzc2V0cy9hcHAvY29tcG9uZW50cy9ldmVudHBhZ2UvZXZlbnRwYWdlLmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9Vc2Vycy9TaGVyaW4vT3ptZW50YTJLMTcvYXNzZXRzL2FwcC9jb21wb25lbnRzL2V2ZW50cGFnZS9ldmVudHBhZ2UuY29tcG9uZW50LnRzIiwibmc6Ly8vQzovVXNlcnMvU2hlcmluL096bWVudGEySzE3L2Fzc2V0cy9hcHAvY29tcG9uZW50cy9ldmVudHBhZ2UvZXZlbnRwYWdlLmNvbXBvbmVudC50cy5FdmVudFBhZ2VDb21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCI8YXBwLWV2ZW50cGFnZT48L2FwcC1ldmVudHBhZ2U+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7O29CQ0FBO01BQUE7bUNBQUEsVUFBQTtNQUFBOzs7In0=
