/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './teventpage.component.css.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from './teventpage.component';
const styles_TEventPageComponent:any[] = [i0.styles];
export const RenderType_TEventPageComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_TEventPageComponent,data:{}});
export function View_TEventPageComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'h1',([] as any[]),
      (null as any),(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i1.ɵted((null as any),['This is events page']))],(null as any),(null as any));
}
export function View_TEventPageComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'app-eventpage',
      ([] as any[]),(null as any),(null as any),(null as any),View_TEventPageComponent_0,
      RenderType_TEventPageComponent)),i1.ɵdid(49152,(null as any),0,i2.TEventPageComponent,
      ([] as any[]),(null as any),(null as any))],(null as any),(null as any));
}
export const TEventPageComponentNgFactory:i1.ComponentFactory<i2.TEventPageComponent> = i1.ɵccf('app-eventpage',
    i2.TEventPageComponent,View_TEventPageComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvU2hlcmluL096bWVudGEySzE3L2Fzc2V0cy9hcHAvY29tcG9uZW50cy90ZXZlbnRwYWdlL3RldmVudHBhZ2UuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L1VzZXJzL1NoZXJpbi9Pem1lbnRhMksxNy9hc3NldHMvYXBwL2NvbXBvbmVudHMvdGV2ZW50cGFnZS90ZXZlbnRwYWdlLmNvbXBvbmVudC50cyIsIm5nOi8vL0M6L1VzZXJzL1NoZXJpbi9Pem1lbnRhMksxNy9hc3NldHMvYXBwL2NvbXBvbmVudHMvdGV2ZW50cGFnZS90ZXZlbnRwYWdlLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vQzovVXNlcnMvU2hlcmluL096bWVudGEySzE3L2Fzc2V0cy9hcHAvY29tcG9uZW50cy90ZXZlbnRwYWdlL3RldmVudHBhZ2UuY29tcG9uZW50LnRzLlRFdmVudFBhZ2VDb21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCI8aDE+VGhpcyBpcyBldmVudHMgcGFnZTwvaDE+IiwiPGFwcC1ldmVudHBhZ2U+PC9hcHAtZXZlbnRwYWdlPiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7OztvQkNBQTtNQUFBLHdFQUFJO2FBQUE7OztvQkNBSjtNQUFBO29DQUFBLFVBQUE7TUFBQTs7OyJ9
