/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './app.module';
import * as i2 from './app.component';
import * as i3 from '../../node_modules/@angular/material/typings/index.ngfactory';
import * as i4 from './components/teventpage/teventpage.component.ngfactory';
import * as i5 from './components/nteventpage/nteventpage.component.ngfactory';
import * as i6 from './components/workshoppage/workshoppage.component.ngfactory';
import * as i7 from './components/contactspage/contactspage.component.ngfactory';
import * as i8 from './components/activateuser/activateuser.component.ngfactory';
import * as i9 from './components/homepage/homepage.component.ngfactory';
import * as i10 from './components/login/login.component.ngfactory';
import * as i11 from './components/register/register.component.ngfactory';
import * as i12 from './components/more/more.component.ngfactory';
import * as i13 from './components/registerevent/registerevent.component.ngfactory';
import * as i14 from './components/cancelevent/cancelevent.component.ngfactory';
import * as i15 from './app.component.ngfactory';
import * as i16 from '@angular/material';
import * as i17 from '@angular/common';
import * as i18 from '@angular/forms';
import * as i19 from '@angular/http';
import * as i20 from '@angular/platform-browser';
import * as i21 from '@angular/animations/browser';
import * as i22 from '@angular/platform-browser/animations';
import * as i23 from '@angular/animations';
import * as i24 from '@angular/flex-layout/media-query/breakpoints/break-points-token';
import * as i25 from '@angular/flex-layout/media-query/breakpoints/break-points-provider';
import * as i26 from '@angular/flex-layout/media-query/breakpoints/break-point-registry';
import * as i27 from '@angular/flex-layout/media-query/match-media';
import * as i28 from '@angular/flex-layout/media-query/media-monitor';
import * as i29 from '@angular/flex-layout/media-query/media-monitor-provider';
import * as i30 from '@angular/flex-layout/media-query/observable-media';
import * as i31 from '@angular/flex-layout/media-query/observable-media-provider';
import * as i32 from '@angular/router';
import * as i33 from './services/user.service';
import * as i34 from './services/more.service';
import * as i35 from './components/teventpage/teventpage.component';
import * as i36 from './components/nteventpage/nteventpage.component';
import * as i37 from './components/workshoppage/workshoppage.component';
import * as i38 from './components/contactspage/contactspage.component';
import * as i39 from './components/activateuser/activateuser.component';
import * as i40 from './components/homepage/homepage.component';
import * as i41 from '@angular/flex-layout/media-query/_module';
import * as i42 from '@angular/flex-layout/flexbox/_module';
export const AppModuleNgFactory:i0.NgModuleFactory<i1.AppModule> = i0.ɵcmf(i1.AppModule,
    [i2.AppComponent],(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i3.MdDialogContainerNgFactory,i3.MdDatepickerContentNgFactory,i3.MdSnackBarContainerNgFactory,
              i3.SimpleSnackBarNgFactory,i3.TooltipComponentNgFactory,i4.TEventPageComponentNgFactory,
              i5.NTEventPageComponentNgFactory,i6.WorkshopPageComponentNgFactory,i7.ContactsPageComponentNgFactory,
              i8.ActivateUserComponentNgFactory,i9.HomePageComponentNgFactory,i10.LoginComponentNgFactory,
              i11.RegisterComponentNgFactory,i12.MoreComponentNgFactory,i13.RegisterEventComponentNgFactory,
              i14.CancelEventComponentNgFactory,i15.AppComponentNgFactory]],[3,i0.ComponentFactoryResolver],
              i0.NgModuleRef]),i0.ɵmpd(4608,i16.Platform,i16.Platform,([] as any[])),
          i0.ɵmpd(5120,i16.ScrollDispatcher,i16.ɵf,[[3,i16.ScrollDispatcher],i0.NgZone,
              i16.Platform]),i0.ɵmpd(5120,i16.ViewportRuler,i16.ɵd,[[3,i16.ViewportRuler],
              i16.ScrollDispatcher]),i0.ɵmpd(4608,i16.ScrollStrategyOptions,i16.ScrollStrategyOptions,
              [i16.ScrollDispatcher,i16.ViewportRuler]),i0.ɵmpd(5120,i0.LOCALE_ID,
              i0.ɵm,[[3,i0.LOCALE_ID]]),i0.ɵmpd(4608,i17.NgLocalization,i17.NgLocaleLocalization,
              [i0.LOCALE_ID]),i0.ɵmpd(5120,i16.OverlayContainer,i16.ɵb,[[3,i16.OverlayContainer]]),
          i0.ɵmpd(4608,i16.ɵv,i16.ɵv,[i16.ViewportRuler]),i0.ɵmpd(4608,i16.Overlay,
              i16.Overlay,[i16.ScrollStrategyOptions,i16.OverlayContainer,i0.ComponentFactoryResolver,
                  i16.ɵv,i0.ApplicationRef,i0.Injector,i0.NgZone]),i0.ɵmpd(5120,i16.FocusOriginMonitor,
              i16.FOCUS_ORIGIN_MONITOR_PROVIDER_FACTORY,[[3,i16.FocusOriginMonitor],
                  i0.NgZone,i16.Platform]),i0.ɵmpd(4608,i18.ɵi,i18.ɵi,([] as any[])),
          i0.ɵmpd(5120,i16.UniqueSelectionDispatcher,i16.ɵj,[[3,i16.UniqueSelectionDispatcher]]),
          i0.ɵmpd(4608,i16.ɵa,i16.ɵa,([] as any[])),i0.ɵmpd(4608,i16.InteractivityChecker,
              i16.InteractivityChecker,[i16.Platform]),i0.ɵmpd(4608,i16.FocusTrapFactory,
              i16.FocusTrapFactory,[i16.InteractivityChecker,i16.Platform,i0.NgZone]),
          i0.ɵmpd(5120,i16.LiveAnnouncer,i16.ɵi,[[3,i16.LiveAnnouncer],[2,i16.LIVE_ANNOUNCER_ELEMENT_TOKEN],
              i16.Platform]),i0.ɵmpd(4608,i16.MdDialog,i16.MdDialog,[i16.Overlay,i0.Injector,
              [2,i17.Location],[3,i16.MdDialog]]),i0.ɵmpd(4608,i16.MdDatepickerIntl,
              i16.MdDatepickerIntl,([] as any[])),i0.ɵmpd(4608,i19.BrowserXhr,i19.BrowserXhr,
              ([] as any[])),i0.ɵmpd(4608,i19.ResponseOptions,i19.BaseResponseOptions,
              ([] as any[])),i0.ɵmpd(5120,i19.XSRFStrategy,i19.ɵb,([] as any[])),i0.ɵmpd(4608,
              i19.XHRBackend,i19.XHRBackend,[i19.BrowserXhr,i19.ResponseOptions,i19.XSRFStrategy]),
          i0.ɵmpd(4608,i19.RequestOptions,i19.BaseRequestOptions,([] as any[])),i0.ɵmpd(5120,
              i19.Http,i19.ɵc,[i19.XHRBackend,i19.RequestOptions]),i0.ɵmpd(4608,i20.DomSanitizer,
              i20.ɵe,[i20.DOCUMENT]),i0.ɵmpd(5120,i16.MdIconRegistry,i16.ICON_REGISTRY_PROVIDER_FACTORY,
              [[3,i16.MdIconRegistry],[2,i19.Http],i20.DomSanitizer]),i0.ɵmpd(4608,
              i20.HAMMER_GESTURE_CONFIG,i20.HammerGestureConfig,([] as any[])),i0.ɵmpd(4608,
              i16.MdSnackBar,i16.MdSnackBar,[i16.Overlay,i16.LiveAnnouncer,[3,i16.MdSnackBar]]),
          i0.ɵmpd(5120,i0.APP_ID,i0.ɵf,([] as any[])),i0.ɵmpd(5120,i0.IterableDiffers,
              i0.ɵk,([] as any[])),i0.ɵmpd(5120,i0.KeyValueDiffers,i0.ɵl,([] as any[])),
          i0.ɵmpd(6144,i0.Sanitizer,(null as any),[i20.DomSanitizer]),i0.ɵmpd(5120,
              i20.EVENT_MANAGER_PLUGINS,(p0_0:any,p1_0:any,p2_0:any,p2_1:any) => {
                return [new i20.ɵDomEventsPlugin(p0_0),new i20.ɵKeyEventsPlugin(p1_0),
                    new i20.ɵHammerGesturesPlugin(p2_0,p2_1)];
              },[i20.DOCUMENT,i20.DOCUMENT,i20.DOCUMENT,i20.HAMMER_GESTURE_CONFIG]),
          i0.ɵmpd(4608,i20.EventManager,i20.EventManager,[i20.EVENT_MANAGER_PLUGINS,
              i0.NgZone]),i0.ɵmpd(135680,i20.ɵDomSharedStylesHost,i20.ɵDomSharedStylesHost,
              [i20.DOCUMENT]),i0.ɵmpd(4608,i20.ɵDomRendererFactory2,i20.ɵDomRendererFactory2,
              [i20.EventManager,i20.ɵDomSharedStylesHost]),i0.ɵmpd(5120,i21.AnimationDriver,
              i22.ɵc,([] as any[])),i0.ɵmpd(5120,i21.ɵAnimationStyleNormalizer,i22.ɵd,
              ([] as any[])),i0.ɵmpd(4608,i21.ɵAnimationEngine,i22.ɵb,[i21.AnimationDriver,
              i21.ɵAnimationStyleNormalizer]),i0.ɵmpd(5120,i0.RendererFactory2,i22.ɵe,
              [i20.ɵDomRendererFactory2,i21.ɵAnimationEngine,i0.NgZone]),i0.ɵmpd(6144,
              i20.ɵSharedStylesHost,(null as any),[i20.ɵDomSharedStylesHost]),i0.ɵmpd(4608,
              i0.Testability,i0.Testability,[i0.NgZone]),i0.ɵmpd(4608,i20.Meta,i20.Meta,
              [i20.DOCUMENT]),i0.ɵmpd(4608,i20.Title,i20.Title,[i20.DOCUMENT]),i0.ɵmpd(4608,
              i23.AnimationBuilder,i22.ɵBrowserAnimationBuilder,[i0.RendererFactory2]),
          i0.ɵmpd(4608,i18.FormBuilder,i18.FormBuilder,([] as any[])),i0.ɵmpd(5120,
              i24.BREAKPOINTS,i25.DEFAULT_BREAKPOINTS_PROVIDER_FACTORY,([] as any[])),
          i0.ɵmpd(4608,i26.BreakPointRegistry,i26.BreakPointRegistry,[i24.BREAKPOINTS]),
          i0.ɵmpd(4608,i27.MatchMedia,i27.MatchMedia,[i0.NgZone]),i0.ɵmpd(5120,i28.MediaMonitor,
              i29.MEDIA_MONITOR_PROVIDER_FACTORY,[[3,i28.MediaMonitor],i26.BreakPointRegistry,
                  i27.MatchMedia]),i0.ɵmpd(5120,i30.ObservableMedia,i31.OBSERVABLE_MEDIA_PROVIDER_FACTORY,
              [[3,i30.ObservableMedia],i27.MatchMedia,i26.BreakPointRegistry]),i0.ɵmpd(5120,
              i32.ActivatedRoute,i32.ɵf,[i32.Router]),i0.ɵmpd(4608,i32.NoPreloading,
              i32.NoPreloading,([] as any[])),i0.ɵmpd(6144,i32.PreloadingStrategy,
              (null as any),[i32.NoPreloading]),i0.ɵmpd(135680,i32.RouterPreloader,
              i32.RouterPreloader,[i32.Router,i0.NgModuleFactoryLoader,i0.Compiler,
                  i0.Injector,i32.PreloadingStrategy]),i0.ɵmpd(4608,i32.PreloadAllModules,
              i32.PreloadAllModules,([] as any[])),i0.ɵmpd(5120,i32.ROUTER_INITIALIZER,
              i32.ɵi,[i32.ɵg]),i0.ɵmpd(5120,i0.APP_BOOTSTRAP_LISTENER,(p0_0:any) => {
            return [p0_0];
          },[i32.ROUTER_INITIALIZER]),i0.ɵmpd(4608,i33.UserService,i33.UserService,
              [i19.Http]),i0.ɵmpd(4608,i34.MoreService,i34.MoreService,([] as any[])),
          i0.ɵmpd(512,i16.CompatibilityModule,i16.CompatibilityModule,([] as any[])),
          i0.ɵmpd(256,i16.MATERIAL_SANITY_CHECKS,true,([] as any[])),i0.ɵmpd(512,i16.MdCommonModule,
              i16.MdCommonModule,[[2,i20.DOCUMENT],[2,i16.MATERIAL_SANITY_CHECKS]]),
          i0.ɵmpd(512,i16.PlatformModule,i16.PlatformModule,([] as any[])),i0.ɵmpd(512,
              i16.ScrollDispatchModule,i16.ScrollDispatchModule,([] as any[])),i0.ɵmpd(512,
              i16.MdRippleModule,i16.MdRippleModule,([] as any[])),i0.ɵmpd(512,i17.CommonModule,
              i17.CommonModule,([] as any[])),i0.ɵmpd(512,i16.MdSelectionModule,i16.MdSelectionModule,
              ([] as any[])),i0.ɵmpd(512,i16.MdOptionModule,i16.MdOptionModule,([] as any[])),
          i0.ɵmpd(512,i16.PortalModule,i16.PortalModule,([] as any[])),i0.ɵmpd(512,
              i16.OverlayModule,i16.OverlayModule,([] as any[])),i0.ɵmpd(512,i16.MdAutocompleteModule,
              i16.MdAutocompleteModule,([] as any[])),i0.ɵmpd(512,i16.StyleModule,
              i16.StyleModule,([] as any[])),i0.ɵmpd(512,i16.MdButtonModule,i16.MdButtonModule,
              ([] as any[])),i0.ɵmpd(512,i18.ɵba,i18.ɵba,([] as any[])),i0.ɵmpd(512,
              i18.FormsModule,i18.FormsModule,([] as any[])),i0.ɵmpd(512,i16.MdButtonToggleModule,
              i16.MdButtonToggleModule,([] as any[])),i0.ɵmpd(512,i16.MdCardModule,
              i16.MdCardModule,([] as any[])),i0.ɵmpd(512,i16.MdChipsModule,i16.MdChipsModule,
              ([] as any[])),i0.ɵmpd(512,i16.ObserveContentModule,i16.ObserveContentModule,
              ([] as any[])),i0.ɵmpd(512,i16.MdCheckboxModule,i16.MdCheckboxModule,
              ([] as any[])),i0.ɵmpd(512,i16.A11yModule,i16.A11yModule,([] as any[])),
          i0.ɵmpd(512,i16.MdDialogModule,i16.MdDialogModule,([] as any[])),i0.ɵmpd(512,
              i16.MdDatepickerModule,i16.MdDatepickerModule,([] as any[])),i0.ɵmpd(512,
              i16.MdExpansionModule,i16.MdExpansionModule,([] as any[])),i0.ɵmpd(512,
              i16.MdLineModule,i16.MdLineModule,([] as any[])),i0.ɵmpd(512,i16.MdGridListModule,
              i16.MdGridListModule,([] as any[])),i0.ɵmpd(512,i16.MdIconModule,i16.MdIconModule,
              ([] as any[])),i0.ɵmpd(512,i16.MdInputModule,i16.MdInputModule,([] as any[])),
          i0.ɵmpd(512,i16.MdListModule,i16.MdListModule,([] as any[])),i0.ɵmpd(512,
              i16.MdMenuModule,i16.MdMenuModule,([] as any[])),i0.ɵmpd(512,i16.MdProgressBarModule,
              i16.MdProgressBarModule,([] as any[])),i0.ɵmpd(512,i16.MdProgressSpinnerModule,
              i16.MdProgressSpinnerModule,([] as any[])),i0.ɵmpd(512,i16.MdRadioModule,
              i16.MdRadioModule,([] as any[])),i0.ɵmpd(512,i16.MdSelectModule,i16.MdSelectModule,
              ([] as any[])),i0.ɵmpd(512,i16.MdSidenavModule,i16.MdSidenavModule,([] as any[])),
          i0.ɵmpd(512,i16.RtlModule,i16.RtlModule,([] as any[])),i0.ɵmpd(512,i16.MdSliderModule,
              i16.MdSliderModule,([] as any[])),i0.ɵmpd(512,i16.MdSlideToggleModule,
              i16.MdSlideToggleModule,([] as any[])),i0.ɵmpd(512,i16.MdSnackBarModule,
              i16.MdSnackBarModule,([] as any[])),i0.ɵmpd(512,i16.MdTabsModule,i16.MdTabsModule,
              ([] as any[])),i0.ɵmpd(512,i16.MdToolbarModule,i16.MdToolbarModule,([] as any[])),
          i0.ɵmpd(512,i16.MdTooltipModule,i16.MdTooltipModule,([] as any[])),i0.ɵmpd(512,
              i16.MaterialModule,i16.MaterialModule,([] as any[])),i0.ɵmpd(1024,i0.ErrorHandler,
              i20.ɵa,([] as any[])),i0.ɵmpd(1024,i0.NgProbeToken,() => {
            return [i32.ɵb()];
          },([] as any[])),i0.ɵmpd(512,i32.ɵg,i32.ɵg,[i0.Injector]),i0.ɵmpd(1024,i0.APP_INITIALIZER,
              (p0_0:any,p0_1:any,p1_0:any) => {
                return [i20.ɵc(p0_0,p0_1),i32.ɵh(p1_0)];
              },[[2,i20.NgProbeToken],[2,i0.NgProbeToken],i32.ɵg]),i0.ɵmpd(512,i0.ApplicationInitStatus,
              i0.ApplicationInitStatus,[[2,i0.APP_INITIALIZER]]),i0.ɵmpd(131584,i0.ɵe,
              i0.ɵe,[i0.NgZone,i0.ɵConsole,i0.Injector,i0.ErrorHandler,i0.ComponentFactoryResolver,
                  i0.ApplicationInitStatus]),i0.ɵmpd(2048,i0.ApplicationRef,(null as any),
              [i0.ɵe]),i0.ɵmpd(512,i0.ApplicationModule,i0.ApplicationModule,[i0.ApplicationRef]),
          i0.ɵmpd(512,i20.BrowserModule,i20.BrowserModule,[[3,i20.BrowserModule]]),
          i0.ɵmpd(512,i22.BrowserAnimationsModule,i22.BrowserAnimationsModule,([] as any[])),
          i0.ɵmpd(512,i18.ReactiveFormsModule,i18.ReactiveFormsModule,([] as any[])),
          i0.ɵmpd(512,i19.HttpModule,i19.HttpModule,([] as any[])),i0.ɵmpd(1024,i32.ɵa,
              i32.ɵd,[[3,i32.Router]]),i0.ɵmpd(512,i32.UrlSerializer,i32.DefaultUrlSerializer,
              ([] as any[])),i0.ɵmpd(512,i32.ChildrenOutletContexts,i32.ChildrenOutletContexts,
              ([] as any[])),i0.ɵmpd(256,i32.ROUTER_CONFIGURATION,{},([] as any[])),
          i0.ɵmpd(1024,i17.LocationStrategy,i32.ɵc,[i17.PlatformLocation,[2,i17.APP_BASE_HREF],
              i32.ROUTER_CONFIGURATION]),i0.ɵmpd(512,i17.Location,i17.Location,[i17.LocationStrategy]),
          i0.ɵmpd(512,i0.Compiler,i0.Compiler,([] as any[])),i0.ɵmpd(512,i0.NgModuleFactoryLoader,
              i0.SystemJsNgModuleLoader,[i0.Compiler,[2,i0.SystemJsNgModuleLoaderConfig]]),
          i0.ɵmpd(1024,i32.ROUTES,() => {
            return [[{path:'tevents',component:i35.TEventPageComponent},{path:'ntevents',
                component:i36.NTEventPageComponent},{path:'workshops',component:i37.WorkshopPageComponent},
                {path:'contacts',component:i38.ContactsPageComponent},{path:'activate/:token',
                    component:i39.ActivateUserComponent},{path:'',component:i40.HomePageComponent,
                    pathMatch:'full'}]];
          },([] as any[])),i0.ɵmpd(1024,i32.Router,i32.ɵe,[i0.ApplicationRef,i32.UrlSerializer,
              i32.ChildrenOutletContexts,i17.Location,i0.Injector,i0.NgModuleFactoryLoader,
              i0.Compiler,i32.ROUTES,i32.ROUTER_CONFIGURATION,[2,i32.UrlHandlingStrategy],
              [2,i32.RouteReuseStrategy]]),i0.ɵmpd(512,i32.RouterModule,i32.RouterModule,
              [[2,i32.ɵa],[2,i32.Router]]),i0.ɵmpd(512,i41.MediaQueriesModule,i41.MediaQueriesModule,
              ([] as any[])),i0.ɵmpd(512,i42.FlexLayoutModule,i42.FlexLayoutModule,
              ([] as any[])),i0.ɵmpd(512,i1.AppModule,i1.AppModule,([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvcHJpbmMvRGVza3RvcC9vem1lbnRhMmsxNy9hc3NldHMvYXBwL2FwcC5tb2R1bGUubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vQzovVXNlcnMvcHJpbmMvRGVza3RvcC9vem1lbnRhMmsxNy9hc3NldHMvYXBwL2FwcC5tb2R1bGUudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
