/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './app.module';
import * as i2 from './app.component';
import * as i3 from '../../node_modules/@angular/material/typings/index.ngfactory';
import * as i4 from './components/eventpage/eventpage.component.ngfactory';
import * as i5 from './components/homepage/homepage.component.ngfactory';
import * as i6 from './components/login/login.component.ngfactory';
import * as i7 from './components/register/register.component.ngfactory';
import * as i8 from './app.component.ngfactory';
import * as i9 from '@angular/material';
import * as i10 from '@angular/common';
import * as i11 from '@angular/forms';
import * as i12 from '@angular/platform-browser';
import * as i13 from '@angular/http';
import * as i14 from '@angular/animations/browser';
import * as i15 from '@angular/platform-browser/animations';
import * as i16 from '@angular/animations';
import * as i17 from '@angular/router';
import * as i18 from './components/eventpage/eventpage.component';
import * as i19 from './components/homepage/homepage.component';
export const AppModuleNgFactory:i0.NgModuleFactory<i1.AppModule> = i0.ɵcmf(i1.AppModule,
    [i2.AppComponent],(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i3.MdDialogContainerNgFactory,i3.MdDatepickerContentNgFactory,i3.MdSnackBarContainerNgFactory,
              i3.SimpleSnackBarNgFactory,i3.TooltipComponentNgFactory,i4.EventPageComponentNgFactory,
              i5.HomePageComponentNgFactory,i6.LoginComponentNgFactory,i7.RegisterComponentNgFactory,
              i8.AppComponentNgFactory]],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),
          i0.ɵmpd(4608,i9.Platform,i9.Platform,([] as any[])),i0.ɵmpd(5120,i9.ScrollDispatcher,
              i9.ɵf,[[3,i9.ScrollDispatcher],i0.NgZone,i9.Platform]),i0.ɵmpd(5120,
              i9.ViewportRuler,i9.ɵd,[[3,i9.ViewportRuler],i9.ScrollDispatcher]),i0.ɵmpd(4608,
              i9.ScrollStrategyOptions,i9.ScrollStrategyOptions,[i9.ScrollDispatcher,
                  i9.ViewportRuler]),i0.ɵmpd(5120,i0.LOCALE_ID,i0.ɵm,[[3,i0.LOCALE_ID]]),
          i0.ɵmpd(4608,i10.NgLocalization,i10.NgLocaleLocalization,[i0.LOCALE_ID]),
          i0.ɵmpd(5120,i9.OverlayContainer,i9.ɵb,[[3,i9.OverlayContainer]]),i0.ɵmpd(4608,
              i9.ɵv,i9.ɵv,[i9.ViewportRuler]),i0.ɵmpd(4608,i9.Overlay,i9.Overlay,[i9.ScrollStrategyOptions,
              i9.OverlayContainer,i0.ComponentFactoryResolver,i9.ɵv,i0.ApplicationRef,
              i0.Injector,i0.NgZone]),i0.ɵmpd(5120,i9.FocusOriginMonitor,i9.FOCUS_ORIGIN_MONITOR_PROVIDER_FACTORY,
              [[3,i9.FocusOriginMonitor],i0.NgZone,i9.Platform]),i0.ɵmpd(4608,i11.ɵi,
              i11.ɵi,([] as any[])),i0.ɵmpd(5120,i9.UniqueSelectionDispatcher,i9.ɵj,
              [[3,i9.UniqueSelectionDispatcher]]),i0.ɵmpd(4608,i9.ɵa,i9.ɵa,([] as any[])),
          i0.ɵmpd(4608,i9.InteractivityChecker,i9.InteractivityChecker,[i9.Platform]),
          i0.ɵmpd(4608,i9.FocusTrapFactory,i9.FocusTrapFactory,[i9.InteractivityChecker,
              i9.Platform,i0.NgZone]),i0.ɵmpd(5120,i9.LiveAnnouncer,i9.ɵi,[[3,i9.LiveAnnouncer],
              [2,i9.LIVE_ANNOUNCER_ELEMENT_TOKEN],i9.Platform]),i0.ɵmpd(4608,i9.MdDialog,
              i9.MdDialog,[i9.Overlay,i0.Injector,[2,i10.Location],[3,i9.MdDialog]]),
          i0.ɵmpd(4608,i9.MdDatepickerIntl,i9.MdDatepickerIntl,([] as any[])),i0.ɵmpd(4608,
              i12.DomSanitizer,i12.ɵe,[i12.DOCUMENT]),i0.ɵmpd(5120,i9.MdIconRegistry,
              i9.ICON_REGISTRY_PROVIDER_FACTORY,[[3,i9.MdIconRegistry],[2,i13.Http],
                  i12.DomSanitizer]),i0.ɵmpd(4608,i12.HAMMER_GESTURE_CONFIG,i12.HammerGestureConfig,
              ([] as any[])),i0.ɵmpd(4608,i9.MdSnackBar,i9.MdSnackBar,[i9.Overlay,
              i9.LiveAnnouncer,[3,i9.MdSnackBar]]),i0.ɵmpd(5120,i0.APP_ID,i0.ɵf,([] as any[])),
          i0.ɵmpd(5120,i0.IterableDiffers,i0.ɵk,([] as any[])),i0.ɵmpd(5120,i0.KeyValueDiffers,
              i0.ɵl,([] as any[])),i0.ɵmpd(6144,i0.Sanitizer,(null as any),[i12.DomSanitizer]),
          i0.ɵmpd(5120,i12.EVENT_MANAGER_PLUGINS,(p0_0:any,p1_0:any,p2_0:any,p2_1:any) => {
            return [new i12.ɵDomEventsPlugin(p0_0),new i12.ɵKeyEventsPlugin(p1_0),
                new i12.ɵHammerGesturesPlugin(p2_0,p2_1)];
          },[i12.DOCUMENT,i12.DOCUMENT,i12.DOCUMENT,i12.HAMMER_GESTURE_CONFIG]),i0.ɵmpd(4608,
              i12.EventManager,i12.EventManager,[i12.EVENT_MANAGER_PLUGINS,i0.NgZone]),
          i0.ɵmpd(135680,i12.ɵDomSharedStylesHost,i12.ɵDomSharedStylesHost,[i12.DOCUMENT]),
          i0.ɵmpd(4608,i12.ɵDomRendererFactory2,i12.ɵDomRendererFactory2,[i12.EventManager,
              i12.ɵDomSharedStylesHost]),i0.ɵmpd(5120,i14.AnimationDriver,i15.ɵc,([] as any[])),
          i0.ɵmpd(5120,i14.ɵAnimationStyleNormalizer,i15.ɵd,([] as any[])),i0.ɵmpd(4608,
              i14.ɵAnimationEngine,i15.ɵb,[i14.AnimationDriver,i14.ɵAnimationStyleNormalizer]),
          i0.ɵmpd(5120,i0.RendererFactory2,i15.ɵe,[i12.ɵDomRendererFactory2,i14.ɵAnimationEngine,
              i0.NgZone]),i0.ɵmpd(6144,i12.ɵSharedStylesHost,(null as any),[i12.ɵDomSharedStylesHost]),
          i0.ɵmpd(4608,i0.Testability,i0.Testability,[i0.NgZone]),i0.ɵmpd(4608,i12.Meta,
              i12.Meta,[i12.DOCUMENT]),i0.ɵmpd(4608,i12.Title,i12.Title,[i12.DOCUMENT]),
          i0.ɵmpd(4608,i16.AnimationBuilder,i15.ɵBrowserAnimationBuilder,[i0.RendererFactory2]),
          i0.ɵmpd(4608,i11.FormBuilder,i11.FormBuilder,([] as any[])),i0.ɵmpd(5120,
              i17.ActivatedRoute,i17.ɵf,[i17.Router]),i0.ɵmpd(4608,i17.NoPreloading,
              i17.NoPreloading,([] as any[])),i0.ɵmpd(6144,i17.PreloadingStrategy,
              (null as any),[i17.NoPreloading]),i0.ɵmpd(135680,i17.RouterPreloader,
              i17.RouterPreloader,[i17.Router,i0.NgModuleFactoryLoader,i0.Compiler,
                  i0.Injector,i17.PreloadingStrategy]),i0.ɵmpd(4608,i17.PreloadAllModules,
              i17.PreloadAllModules,([] as any[])),i0.ɵmpd(5120,i17.ROUTER_INITIALIZER,
              i17.ɵi,[i17.ɵg]),i0.ɵmpd(5120,i0.APP_BOOTSTRAP_LISTENER,(p0_0:any) => {
            return [p0_0];
          },[i17.ROUTER_INITIALIZER]),i0.ɵmpd(512,i9.CompatibilityModule,i9.CompatibilityModule,
              ([] as any[])),i0.ɵmpd(256,i9.MATERIAL_SANITY_CHECKS,true,([] as any[])),
          i0.ɵmpd(512,i9.MdCommonModule,i9.MdCommonModule,[[2,i12.DOCUMENT],[2,i9.MATERIAL_SANITY_CHECKS]]),
          i0.ɵmpd(512,i9.PlatformModule,i9.PlatformModule,([] as any[])),i0.ɵmpd(512,
              i9.ScrollDispatchModule,i9.ScrollDispatchModule,([] as any[])),i0.ɵmpd(512,
              i9.MdRippleModule,i9.MdRippleModule,([] as any[])),i0.ɵmpd(512,i10.CommonModule,
              i10.CommonModule,([] as any[])),i0.ɵmpd(512,i9.MdSelectionModule,i9.MdSelectionModule,
              ([] as any[])),i0.ɵmpd(512,i9.MdOptionModule,i9.MdOptionModule,([] as any[])),
          i0.ɵmpd(512,i9.PortalModule,i9.PortalModule,([] as any[])),i0.ɵmpd(512,i9.OverlayModule,
              i9.OverlayModule,([] as any[])),i0.ɵmpd(512,i9.MdAutocompleteModule,
              i9.MdAutocompleteModule,([] as any[])),i0.ɵmpd(512,i9.StyleModule,i9.StyleModule,
              ([] as any[])),i0.ɵmpd(512,i9.MdButtonModule,i9.MdButtonModule,([] as any[])),
          i0.ɵmpd(512,i11.ɵba,i11.ɵba,([] as any[])),i0.ɵmpd(512,i11.FormsModule,i11.FormsModule,
              ([] as any[])),i0.ɵmpd(512,i9.MdButtonToggleModule,i9.MdButtonToggleModule,
              ([] as any[])),i0.ɵmpd(512,i9.MdCardModule,i9.MdCardModule,([] as any[])),
          i0.ɵmpd(512,i9.MdChipsModule,i9.MdChipsModule,([] as any[])),i0.ɵmpd(512,
              i9.ObserveContentModule,i9.ObserveContentModule,([] as any[])),i0.ɵmpd(512,
              i9.MdCheckboxModule,i9.MdCheckboxModule,([] as any[])),i0.ɵmpd(512,i9.A11yModule,
              i9.A11yModule,([] as any[])),i0.ɵmpd(512,i9.MdDialogModule,i9.MdDialogModule,
              ([] as any[])),i0.ɵmpd(512,i9.MdDatepickerModule,i9.MdDatepickerModule,
              ([] as any[])),i0.ɵmpd(512,i9.MdExpansionModule,i9.MdExpansionModule,
              ([] as any[])),i0.ɵmpd(512,i9.MdLineModule,i9.MdLineModule,([] as any[])),
          i0.ɵmpd(512,i9.MdGridListModule,i9.MdGridListModule,([] as any[])),i0.ɵmpd(512,
              i9.MdIconModule,i9.MdIconModule,([] as any[])),i0.ɵmpd(512,i9.MdInputModule,
              i9.MdInputModule,([] as any[])),i0.ɵmpd(512,i9.MdListModule,i9.MdListModule,
              ([] as any[])),i0.ɵmpd(512,i9.MdMenuModule,i9.MdMenuModule,([] as any[])),
          i0.ɵmpd(512,i9.MdProgressBarModule,i9.MdProgressBarModule,([] as any[])),
          i0.ɵmpd(512,i9.MdProgressSpinnerModule,i9.MdProgressSpinnerModule,([] as any[])),
          i0.ɵmpd(512,i9.MdRadioModule,i9.MdRadioModule,([] as any[])),i0.ɵmpd(512,
              i9.MdSelectModule,i9.MdSelectModule,([] as any[])),i0.ɵmpd(512,i9.MdSidenavModule,
              i9.MdSidenavModule,([] as any[])),i0.ɵmpd(512,i9.RtlModule,i9.RtlModule,
              ([] as any[])),i0.ɵmpd(512,i9.MdSliderModule,i9.MdSliderModule,([] as any[])),
          i0.ɵmpd(512,i9.MdSlideToggleModule,i9.MdSlideToggleModule,([] as any[])),
          i0.ɵmpd(512,i9.MdSnackBarModule,i9.MdSnackBarModule,([] as any[])),i0.ɵmpd(512,
              i9.MdTabsModule,i9.MdTabsModule,([] as any[])),i0.ɵmpd(512,i9.MdToolbarModule,
              i9.MdToolbarModule,([] as any[])),i0.ɵmpd(512,i9.MdTooltipModule,i9.MdTooltipModule,
              ([] as any[])),i0.ɵmpd(512,i9.MaterialModule,i9.MaterialModule,([] as any[])),
          i0.ɵmpd(1024,i0.ErrorHandler,i12.ɵa,([] as any[])),i0.ɵmpd(1024,i0.NgProbeToken,
              () => {
                return [i17.ɵb()];
              },([] as any[])),i0.ɵmpd(512,i17.ɵg,i17.ɵg,[i0.Injector]),i0.ɵmpd(1024,
              i0.APP_INITIALIZER,(p0_0:any,p0_1:any,p1_0:any) => {
                return [i12.ɵc(p0_0,p0_1),i17.ɵh(p1_0)];
              },[[2,i12.NgProbeToken],[2,i0.NgProbeToken],i17.ɵg]),i0.ɵmpd(512,i0.ApplicationInitStatus,
              i0.ApplicationInitStatus,[[2,i0.APP_INITIALIZER]]),i0.ɵmpd(131584,i0.ɵe,
              i0.ɵe,[i0.NgZone,i0.ɵConsole,i0.Injector,i0.ErrorHandler,i0.ComponentFactoryResolver,
                  i0.ApplicationInitStatus]),i0.ɵmpd(2048,i0.ApplicationRef,(null as any),
              [i0.ɵe]),i0.ɵmpd(512,i0.ApplicationModule,i0.ApplicationModule,[i0.ApplicationRef]),
          i0.ɵmpd(512,i12.BrowserModule,i12.BrowserModule,[[3,i12.BrowserModule]]),
          i0.ɵmpd(512,i15.BrowserAnimationsModule,i15.BrowserAnimationsModule,([] as any[])),
          i0.ɵmpd(512,i11.ReactiveFormsModule,i11.ReactiveFormsModule,([] as any[])),
          i0.ɵmpd(1024,i17.ɵa,i17.ɵd,[[3,i17.Router]]),i0.ɵmpd(512,i17.UrlSerializer,
              i17.DefaultUrlSerializer,([] as any[])),i0.ɵmpd(512,i17.ChildrenOutletContexts,
              i17.ChildrenOutletContexts,([] as any[])),i0.ɵmpd(256,i17.ROUTER_CONFIGURATION,
              {},([] as any[])),i0.ɵmpd(1024,i10.LocationStrategy,i17.ɵc,[i10.PlatformLocation,
              [2,i10.APP_BASE_HREF],i17.ROUTER_CONFIGURATION]),i0.ɵmpd(512,i10.Location,
              i10.Location,[i10.LocationStrategy]),i0.ɵmpd(512,i0.Compiler,i0.Compiler,
              ([] as any[])),i0.ɵmpd(512,i0.NgModuleFactoryLoader,i0.SystemJsNgModuleLoader,
              [i0.Compiler,[2,i0.SystemJsNgModuleLoaderConfig]]),i0.ɵmpd(1024,i17.ROUTES,
              () => {
                return [[{path:'event',component:i18.EventPageComponent},{path:'',
                    component:i19.HomePageComponent,pathMatch:'full'}]];
              },([] as any[])),i0.ɵmpd(1024,i17.Router,i17.ɵe,[i0.ApplicationRef,i17.UrlSerializer,
              i17.ChildrenOutletContexts,i10.Location,i0.Injector,i0.NgModuleFactoryLoader,
              i0.Compiler,i17.ROUTES,i17.ROUTER_CONFIGURATION,[2,i17.UrlHandlingStrategy],
              [2,i17.RouteReuseStrategy]]),i0.ɵmpd(512,i17.RouterModule,i17.RouterModule,
              [[2,i17.ɵa],[2,i17.Router]]),i0.ɵmpd(512,i1.AppModule,i1.AppModule,([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvU2hlcmluL096bWVudGEySzE3L2Fzc2V0cy9hcHAvYXBwLm1vZHVsZS5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9Vc2Vycy9TaGVyaW4vT3ptZW50YTJLMTcvYXNzZXRzL2FwcC9hcHAubW9kdWxlLnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzsifQ==
