/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './app.module';
import * as i2 from './app.component';
import * as i3 from '../../node_modules/@angular/material/typings/index.ngfactory';
import * as i4 from './components/teventpage/teventpage.component.ngfactory';
import * as i5 from './components/nteventpage/nteventpage.component.ngfactory';
import * as i6 from './components/workshoppage/workshoppage.component.ngfactory';
import * as i7 from './components/contactspage/contactspage.component.ngfactory';
import * as i8 from './components/activateuser/activateuser.component.ngfactory';
import * as i9 from './components/homepage/homepage.component.ngfactory';
import * as i10 from './components/login/login.component.ngfactory';
import * as i11 from './components/register/register.component.ngfactory';
import * as i12 from './components/more/more.component.ngfactory';
import * as i13 from './components/registerevent/registerevent.component.ngfactory';
import * as i14 from './app.component.ngfactory';
import * as i15 from '@angular/material';
import * as i16 from '@angular/common';
import * as i17 from '@angular/forms';
import * as i18 from '@angular/http';
import * as i19 from '@angular/platform-browser';
import * as i20 from '@angular/animations/browser';
import * as i21 from '@angular/platform-browser/animations';
import * as i22 from '@angular/animations';
import * as i23 from '@angular/flex-layout/media-query/breakpoints/break-points-token';
import * as i24 from '@angular/flex-layout/media-query/breakpoints/break-points-provider';
import * as i25 from '@angular/flex-layout/media-query/breakpoints/break-point-registry';
import * as i26 from '@angular/flex-layout/media-query/match-media';
import * as i27 from '@angular/flex-layout/media-query/media-monitor';
import * as i28 from '@angular/flex-layout/media-query/media-monitor-provider';
import * as i29 from '@angular/flex-layout/media-query/observable-media';
import * as i30 from '@angular/flex-layout/media-query/observable-media-provider';
import * as i31 from '@angular/router';
import * as i32 from './services/user.service';
import * as i33 from './services/more.service';
import * as i34 from './components/teventpage/teventpage.component';
import * as i35 from './components/nteventpage/nteventpage.component';
import * as i36 from './components/workshoppage/workshoppage.component';
import * as i37 from './components/contactspage/contactspage.component';
import * as i38 from './components/activateuser/activateuser.component';
import * as i39 from './components/homepage/homepage.component';
import * as i40 from '@angular/flex-layout/media-query/_module';
import * as i41 from '@angular/flex-layout/flexbox/_module';
export const AppModuleNgFactory:i0.NgModuleFactory<i1.AppModule> = i0.ɵcmf(i1.AppModule,
    [i2.AppComponent],(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i3.MdDialogContainerNgFactory,i3.MdDatepickerContentNgFactory,i3.MdSnackBarContainerNgFactory,
              i3.SimpleSnackBarNgFactory,i3.TooltipComponentNgFactory,i4.TEventPageComponentNgFactory,
              i5.NTEventPageComponentNgFactory,i6.WorkshopPageComponentNgFactory,i7.ContactsPageComponentNgFactory,
              i8.ActivateUserComponentNgFactory,i9.HomePageComponentNgFactory,i10.LoginComponentNgFactory,
              i11.RegisterComponentNgFactory,i12.MoreComponentNgFactory,i13.RegisterEventComponentNgFactory,
              i14.AppComponentNgFactory]],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),
          i0.ɵmpd(4608,i15.Platform,i15.Platform,([] as any[])),i0.ɵmpd(5120,i15.ScrollDispatcher,
              i15.ɵf,[[3,i15.ScrollDispatcher],i0.NgZone,i15.Platform]),i0.ɵmpd(5120,
              i15.ViewportRuler,i15.ɵd,[[3,i15.ViewportRuler],i15.ScrollDispatcher]),
          i0.ɵmpd(4608,i15.ScrollStrategyOptions,i15.ScrollStrategyOptions,[i15.ScrollDispatcher,
              i15.ViewportRuler]),i0.ɵmpd(5120,i0.LOCALE_ID,i0.ɵm,[[3,i0.LOCALE_ID]]),
          i0.ɵmpd(4608,i16.NgLocalization,i16.NgLocaleLocalization,[i0.LOCALE_ID]),
          i0.ɵmpd(5120,i15.OverlayContainer,i15.ɵb,[[3,i15.OverlayContainer]]),i0.ɵmpd(4608,
              i15.ɵv,i15.ɵv,[i15.ViewportRuler]),i0.ɵmpd(4608,i15.Overlay,i15.Overlay,
              [i15.ScrollStrategyOptions,i15.OverlayContainer,i0.ComponentFactoryResolver,
                  i15.ɵv,i0.ApplicationRef,i0.Injector,i0.NgZone]),i0.ɵmpd(5120,i15.FocusOriginMonitor,
              i15.FOCUS_ORIGIN_MONITOR_PROVIDER_FACTORY,[[3,i15.FocusOriginMonitor],
                  i0.NgZone,i15.Platform]),i0.ɵmpd(4608,i17.ɵi,i17.ɵi,([] as any[])),
          i0.ɵmpd(5120,i15.UniqueSelectionDispatcher,i15.ɵj,[[3,i15.UniqueSelectionDispatcher]]),
          i0.ɵmpd(4608,i15.ɵa,i15.ɵa,([] as any[])),i0.ɵmpd(4608,i15.InteractivityChecker,
              i15.InteractivityChecker,[i15.Platform]),i0.ɵmpd(4608,i15.FocusTrapFactory,
              i15.FocusTrapFactory,[i15.InteractivityChecker,i15.Platform,i0.NgZone]),
          i0.ɵmpd(5120,i15.LiveAnnouncer,i15.ɵi,[[3,i15.LiveAnnouncer],[2,i15.LIVE_ANNOUNCER_ELEMENT_TOKEN],
              i15.Platform]),i0.ɵmpd(4608,i15.MdDialog,i15.MdDialog,[i15.Overlay,i0.Injector,
              [2,i16.Location],[3,i15.MdDialog]]),i0.ɵmpd(4608,i15.MdDatepickerIntl,
              i15.MdDatepickerIntl,([] as any[])),i0.ɵmpd(4608,i18.BrowserXhr,i18.BrowserXhr,
              ([] as any[])),i0.ɵmpd(4608,i18.ResponseOptions,i18.BaseResponseOptions,
              ([] as any[])),i0.ɵmpd(5120,i18.XSRFStrategy,i18.ɵb,([] as any[])),i0.ɵmpd(4608,
              i18.XHRBackend,i18.XHRBackend,[i18.BrowserXhr,i18.ResponseOptions,i18.XSRFStrategy]),
          i0.ɵmpd(4608,i18.RequestOptions,i18.BaseRequestOptions,([] as any[])),i0.ɵmpd(5120,
              i18.Http,i18.ɵc,[i18.XHRBackend,i18.RequestOptions]),i0.ɵmpd(4608,i19.DomSanitizer,
              i19.ɵe,[i19.DOCUMENT]),i0.ɵmpd(5120,i15.MdIconRegistry,i15.ICON_REGISTRY_PROVIDER_FACTORY,
              [[3,i15.MdIconRegistry],[2,i18.Http],i19.DomSanitizer]),i0.ɵmpd(4608,
              i19.HAMMER_GESTURE_CONFIG,i19.HammerGestureConfig,([] as any[])),i0.ɵmpd(4608,
              i15.MdSnackBar,i15.MdSnackBar,[i15.Overlay,i15.LiveAnnouncer,[3,i15.MdSnackBar]]),
          i0.ɵmpd(5120,i0.APP_ID,i0.ɵf,([] as any[])),i0.ɵmpd(5120,i0.IterableDiffers,
              i0.ɵk,([] as any[])),i0.ɵmpd(5120,i0.KeyValueDiffers,i0.ɵl,([] as any[])),
          i0.ɵmpd(6144,i0.Sanitizer,(null as any),[i19.DomSanitizer]),i0.ɵmpd(5120,
              i19.EVENT_MANAGER_PLUGINS,(p0_0:any,p1_0:any,p2_0:any,p2_1:any) => {
                return [new i19.ɵDomEventsPlugin(p0_0),new i19.ɵKeyEventsPlugin(p1_0),
                    new i19.ɵHammerGesturesPlugin(p2_0,p2_1)];
              },[i19.DOCUMENT,i19.DOCUMENT,i19.DOCUMENT,i19.HAMMER_GESTURE_CONFIG]),
          i0.ɵmpd(4608,i19.EventManager,i19.EventManager,[i19.EVENT_MANAGER_PLUGINS,
              i0.NgZone]),i0.ɵmpd(135680,i19.ɵDomSharedStylesHost,i19.ɵDomSharedStylesHost,
              [i19.DOCUMENT]),i0.ɵmpd(4608,i19.ɵDomRendererFactory2,i19.ɵDomRendererFactory2,
              [i19.EventManager,i19.ɵDomSharedStylesHost]),i0.ɵmpd(5120,i20.AnimationDriver,
              i21.ɵc,([] as any[])),i0.ɵmpd(5120,i20.ɵAnimationStyleNormalizer,i21.ɵd,
              ([] as any[])),i0.ɵmpd(4608,i20.ɵAnimationEngine,i21.ɵb,[i20.AnimationDriver,
              i20.ɵAnimationStyleNormalizer]),i0.ɵmpd(5120,i0.RendererFactory2,i21.ɵe,
              [i19.ɵDomRendererFactory2,i20.ɵAnimationEngine,i0.NgZone]),i0.ɵmpd(6144,
              i19.ɵSharedStylesHost,(null as any),[i19.ɵDomSharedStylesHost]),i0.ɵmpd(4608,
              i0.Testability,i0.Testability,[i0.NgZone]),i0.ɵmpd(4608,i19.Meta,i19.Meta,
              [i19.DOCUMENT]),i0.ɵmpd(4608,i19.Title,i19.Title,[i19.DOCUMENT]),i0.ɵmpd(4608,
              i22.AnimationBuilder,i21.ɵBrowserAnimationBuilder,[i0.RendererFactory2]),
          i0.ɵmpd(4608,i17.FormBuilder,i17.FormBuilder,([] as any[])),i0.ɵmpd(5120,
              i23.BREAKPOINTS,i24.DEFAULT_BREAKPOINTS_PROVIDER_FACTORY,([] as any[])),
          i0.ɵmpd(4608,i25.BreakPointRegistry,i25.BreakPointRegistry,[i23.BREAKPOINTS]),
          i0.ɵmpd(4608,i26.MatchMedia,i26.MatchMedia,[i0.NgZone]),i0.ɵmpd(5120,i27.MediaMonitor,
              i28.MEDIA_MONITOR_PROVIDER_FACTORY,[[3,i27.MediaMonitor],i25.BreakPointRegistry,
                  i26.MatchMedia]),i0.ɵmpd(5120,i29.ObservableMedia,i30.OBSERVABLE_MEDIA_PROVIDER_FACTORY,
              [[3,i29.ObservableMedia],i26.MatchMedia,i25.BreakPointRegistry]),i0.ɵmpd(5120,
              i31.ActivatedRoute,i31.ɵf,[i31.Router]),i0.ɵmpd(4608,i31.NoPreloading,
              i31.NoPreloading,([] as any[])),i0.ɵmpd(6144,i31.PreloadingStrategy,
              (null as any),[i31.NoPreloading]),i0.ɵmpd(135680,i31.RouterPreloader,
              i31.RouterPreloader,[i31.Router,i0.NgModuleFactoryLoader,i0.Compiler,
                  i0.Injector,i31.PreloadingStrategy]),i0.ɵmpd(4608,i31.PreloadAllModules,
              i31.PreloadAllModules,([] as any[])),i0.ɵmpd(5120,i31.ROUTER_INITIALIZER,
              i31.ɵi,[i31.ɵg]),i0.ɵmpd(5120,i0.APP_BOOTSTRAP_LISTENER,(p0_0:any) => {
            return [p0_0];
          },[i31.ROUTER_INITIALIZER]),i0.ɵmpd(4608,i32.UserService,i32.UserService,
              [i18.Http]),i0.ɵmpd(4608,i33.MoreService,i33.MoreService,([] as any[])),
          i0.ɵmpd(512,i15.CompatibilityModule,i15.CompatibilityModule,([] as any[])),
          i0.ɵmpd(256,i15.MATERIAL_SANITY_CHECKS,true,([] as any[])),i0.ɵmpd(512,i15.MdCommonModule,
              i15.MdCommonModule,[[2,i19.DOCUMENT],[2,i15.MATERIAL_SANITY_CHECKS]]),
          i0.ɵmpd(512,i15.PlatformModule,i15.PlatformModule,([] as any[])),i0.ɵmpd(512,
              i15.ScrollDispatchModule,i15.ScrollDispatchModule,([] as any[])),i0.ɵmpd(512,
              i15.MdRippleModule,i15.MdRippleModule,([] as any[])),i0.ɵmpd(512,i16.CommonModule,
              i16.CommonModule,([] as any[])),i0.ɵmpd(512,i15.MdSelectionModule,i15.MdSelectionModule,
              ([] as any[])),i0.ɵmpd(512,i15.MdOptionModule,i15.MdOptionModule,([] as any[])),
          i0.ɵmpd(512,i15.PortalModule,i15.PortalModule,([] as any[])),i0.ɵmpd(512,
              i15.OverlayModule,i15.OverlayModule,([] as any[])),i0.ɵmpd(512,i15.MdAutocompleteModule,
              i15.MdAutocompleteModule,([] as any[])),i0.ɵmpd(512,i15.StyleModule,
              i15.StyleModule,([] as any[])),i0.ɵmpd(512,i15.MdButtonModule,i15.MdButtonModule,
              ([] as any[])),i0.ɵmpd(512,i17.ɵba,i17.ɵba,([] as any[])),i0.ɵmpd(512,
              i17.FormsModule,i17.FormsModule,([] as any[])),i0.ɵmpd(512,i15.MdButtonToggleModule,
              i15.MdButtonToggleModule,([] as any[])),i0.ɵmpd(512,i15.MdCardModule,
              i15.MdCardModule,([] as any[])),i0.ɵmpd(512,i15.MdChipsModule,i15.MdChipsModule,
              ([] as any[])),i0.ɵmpd(512,i15.ObserveContentModule,i15.ObserveContentModule,
              ([] as any[])),i0.ɵmpd(512,i15.MdCheckboxModule,i15.MdCheckboxModule,
              ([] as any[])),i0.ɵmpd(512,i15.A11yModule,i15.A11yModule,([] as any[])),
          i0.ɵmpd(512,i15.MdDialogModule,i15.MdDialogModule,([] as any[])),i0.ɵmpd(512,
              i15.MdDatepickerModule,i15.MdDatepickerModule,([] as any[])),i0.ɵmpd(512,
              i15.MdExpansionModule,i15.MdExpansionModule,([] as any[])),i0.ɵmpd(512,
              i15.MdLineModule,i15.MdLineModule,([] as any[])),i0.ɵmpd(512,i15.MdGridListModule,
              i15.MdGridListModule,([] as any[])),i0.ɵmpd(512,i15.MdIconModule,i15.MdIconModule,
              ([] as any[])),i0.ɵmpd(512,i15.MdInputModule,i15.MdInputModule,([] as any[])),
          i0.ɵmpd(512,i15.MdListModule,i15.MdListModule,([] as any[])),i0.ɵmpd(512,
              i15.MdMenuModule,i15.MdMenuModule,([] as any[])),i0.ɵmpd(512,i15.MdProgressBarModule,
              i15.MdProgressBarModule,([] as any[])),i0.ɵmpd(512,i15.MdProgressSpinnerModule,
              i15.MdProgressSpinnerModule,([] as any[])),i0.ɵmpd(512,i15.MdRadioModule,
              i15.MdRadioModule,([] as any[])),i0.ɵmpd(512,i15.MdSelectModule,i15.MdSelectModule,
              ([] as any[])),i0.ɵmpd(512,i15.MdSidenavModule,i15.MdSidenavModule,([] as any[])),
          i0.ɵmpd(512,i15.RtlModule,i15.RtlModule,([] as any[])),i0.ɵmpd(512,i15.MdSliderModule,
              i15.MdSliderModule,([] as any[])),i0.ɵmpd(512,i15.MdSlideToggleModule,
              i15.MdSlideToggleModule,([] as any[])),i0.ɵmpd(512,i15.MdSnackBarModule,
              i15.MdSnackBarModule,([] as any[])),i0.ɵmpd(512,i15.MdTabsModule,i15.MdTabsModule,
              ([] as any[])),i0.ɵmpd(512,i15.MdToolbarModule,i15.MdToolbarModule,([] as any[])),
          i0.ɵmpd(512,i15.MdTooltipModule,i15.MdTooltipModule,([] as any[])),i0.ɵmpd(512,
              i15.MaterialModule,i15.MaterialModule,([] as any[])),i0.ɵmpd(1024,i0.ErrorHandler,
              i19.ɵa,([] as any[])),i0.ɵmpd(1024,i0.NgProbeToken,() => {
            return [i31.ɵb()];
          },([] as any[])),i0.ɵmpd(512,i31.ɵg,i31.ɵg,[i0.Injector]),i0.ɵmpd(1024,i0.APP_INITIALIZER,
              (p0_0:any,p0_1:any,p1_0:any) => {
                return [i19.ɵc(p0_0,p0_1),i31.ɵh(p1_0)];
              },[[2,i19.NgProbeToken],[2,i0.NgProbeToken],i31.ɵg]),i0.ɵmpd(512,i0.ApplicationInitStatus,
              i0.ApplicationInitStatus,[[2,i0.APP_INITIALIZER]]),i0.ɵmpd(131584,i0.ɵe,
              i0.ɵe,[i0.NgZone,i0.ɵConsole,i0.Injector,i0.ErrorHandler,i0.ComponentFactoryResolver,
                  i0.ApplicationInitStatus]),i0.ɵmpd(2048,i0.ApplicationRef,(null as any),
              [i0.ɵe]),i0.ɵmpd(512,i0.ApplicationModule,i0.ApplicationModule,[i0.ApplicationRef]),
          i0.ɵmpd(512,i19.BrowserModule,i19.BrowserModule,[[3,i19.BrowserModule]]),
          i0.ɵmpd(512,i21.BrowserAnimationsModule,i21.BrowserAnimationsModule,([] as any[])),
          i0.ɵmpd(512,i17.ReactiveFormsModule,i17.ReactiveFormsModule,([] as any[])),
          i0.ɵmpd(512,i18.HttpModule,i18.HttpModule,([] as any[])),i0.ɵmpd(1024,i31.ɵa,
              i31.ɵd,[[3,i31.Router]]),i0.ɵmpd(512,i31.UrlSerializer,i31.DefaultUrlSerializer,
              ([] as any[])),i0.ɵmpd(512,i31.ChildrenOutletContexts,i31.ChildrenOutletContexts,
              ([] as any[])),i0.ɵmpd(256,i31.ROUTER_CONFIGURATION,{},([] as any[])),
          i0.ɵmpd(1024,i16.LocationStrategy,i31.ɵc,[i16.PlatformLocation,[2,i16.APP_BASE_HREF],
              i31.ROUTER_CONFIGURATION]),i0.ɵmpd(512,i16.Location,i16.Location,[i16.LocationStrategy]),
          i0.ɵmpd(512,i0.Compiler,i0.Compiler,([] as any[])),i0.ɵmpd(512,i0.NgModuleFactoryLoader,
              i0.SystemJsNgModuleLoader,[i0.Compiler,[2,i0.SystemJsNgModuleLoaderConfig]]),
          i0.ɵmpd(1024,i31.ROUTES,() => {
            return [[{path:'tevents',component:i34.TEventPageComponent},{path:'ntevents',
                component:i35.NTEventPageComponent},{path:'workshops',component:i36.WorkshopPageComponent},
                {path:'contacts',component:i37.ContactsPageComponent},{path:'activate/:token',
                    component:i38.ActivateUserComponent},{path:'',component:i39.HomePageComponent,
                    pathMatch:'full'}]];
          },([] as any[])),i0.ɵmpd(1024,i31.Router,i31.ɵe,[i0.ApplicationRef,i31.UrlSerializer,
              i31.ChildrenOutletContexts,i16.Location,i0.Injector,i0.NgModuleFactoryLoader,
              i0.Compiler,i31.ROUTES,i31.ROUTER_CONFIGURATION,[2,i31.UrlHandlingStrategy],
              [2,i31.RouteReuseStrategy]]),i0.ɵmpd(512,i31.RouterModule,i31.RouterModule,
              [[2,i31.ɵa],[2,i31.Router]]),i0.ɵmpd(512,i40.MediaQueriesModule,i40.MediaQueriesModule,
              ([] as any[])),i0.ɵmpd(512,i41.FlexLayoutModule,i41.FlexLayoutModule,
              ([] as any[])),i0.ɵmpd(512,i1.AppModule,i1.AppModule,([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvcHJpbmMvRGVza3RvcC9vem1lbnRhMmsxNy9hc3NldHMvYXBwL2FwcC5tb2R1bGUubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vQzovVXNlcnMvcHJpbmMvRGVza3RvcC9vem1lbnRhMmsxNy9hc3NldHMvYXBwL2FwcC5tb2R1bGUudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7In0=
